services:
  - type: web
    name: blog-management-system-laravel
    env: docker
    branch: main
    dockerfilePath: ./Dockerfile
    buildCommand: ""
    startCommand: "/usr/local/bin/docker-entrypoint.sh /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf"
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
